### PR TITLE
add keyword descriptions to meta schemas

### PR DESCRIPTION
**Pull request by mabagoury**
The `$id` description is only added for now to see if updating the node module would make things work correctly.

### CODE REVIEW

**Review by jdesrosiers — COMMENTED** [review]
I'm a little wary of the maintenance requirements of some of the more elaborate descriptions. Let's keep it to relatively simple descriptions. We can include a link to learnjsonschema.com (which I noticed is where you're getting your descriptions anyway) for more information.

**Comment by jdesrosiers** [comment]
Please rebase

**Comment by mabagoury** [comment]
This is still a work in progress. We have a bug rendering the markdown in Neovim. A `\` at the end of the line is rendered as is instead of being interpreted as a hard line break.

**Comment by DarhkVoyd** [comment]
@jdesrosiers We have made the required changes to the description to keep them relatively simpler and easier to maintain.

**Comment by jdesrosiers** [comment]
Looks good other than some linting errors. After you fix the linting errors, please rebase and squash your commits. Then it'll be ready to merge.

**Pull request merged**
